### ISSUE TITLE
Delete useless columns in venice reviews

### ISSUE THREAD

**Issue by VereSchulpen** [VereSchulpen/Super-Host-worth-it-#13]

**Comment by VereSchulpen** [comment]
Keep these:
host id
price
property_type
room_type
superhost
listing count
minimum nights
review_score_rating
review_per_month

**Comment by Davejongenelen** [comment]
**Create table without useless columns**:
code:
Venice_data <- Venice[ c("id","host_id","host_is_superhost","host_listings_count","property_type","room_type","price","minimum_nights","number_of_reviews","review_scores_rating","reviews_per_month") ]
